[2023-06-13T14:52:43.653+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: a_etldag.load_applicants manual__2023-06-13T14:52:38.944382+00:00 [queued]>
[2023-06-13T14:52:43.661+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: a_etldag.load_applicants manual__2023-06-13T14:52:38.944382+00:00 [queued]>
[2023-06-13T14:52:43.662+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-13T14:52:43.677+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_applicants> on 2023-06-13 14:52:38.944382+00:00
[2023-06-13T14:52:43.683+0000] {standard_task_runner.py:57} INFO - Started process 4130 to run task
[2023-06-13T14:52:43.687+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'a_etldag', 'load_applicants', 'manual__2023-06-13T14:52:38.944382+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpwj1cd6kp']
[2023-06-13T14:52:43.688+0000] {standard_task_runner.py:85} INFO - Job 114: Subtask load_applicants
[2023-06-13T14:52:43.735+0000] {task_command.py:410} INFO - Running <TaskInstance: a_etldag.load_applicants manual__2023-06-13T14:52:38.944382+00:00 [running]> on host 9e894d1b1662
[2023-06-13T14:52:43.800+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='a_etldag' AIRFLOW_CTX_TASK_ID='load_applicants' AIRFLOW_CTX_EXECUTION_DATE='2023-06-13T14:52:38.944382+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-13T14:52:38.944382+00:00'
[2023-06-13T14:52:43.811+0000] {base.py:73} INFO - Using connection ID 'sqlserver' for task execution.
[2023-06-13T14:52:43.984+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 461, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (245, b"Conversion failed when converting the nvarchar value 'Age' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 46, in load_applicants
    'class_id'])
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in insert_rows
    cur.execute(sql, values)
  File "src/pymssql/_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute
pymssql._pymssql.OperationalError: (245, b"Conversion failed when converting the nvarchar value 'Age' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2023-06-13T14:52:43.993+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=a_etldag, task_id=load_applicants, execution_date=20230613T145238, start_date=20230613T145243, end_date=20230613T145243
[2023-06-13T14:52:44.006+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 114 for task load_applicants ((245, b"Conversion failed when converting the nvarchar value 'Age' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"); 4130)
[2023-06-13T14:52:44.019+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-13T14:52:44.034+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
